<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('providers')->insert([
            [
                'base_url' => 'https://bilalsadasub.com/api',
                'name' => 'adex server 1',
                'username' => 'qwest',
                'password' => 'qwest123',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'adex',
            ],
            [
                'base_url' => '#',
                'name' => 'adex server 2',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'adex',
            ],
            [
                'base_url' => '#',
                'name' => 'adex server 3',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'adex',
            ],
            [
                'base_url' => '#',
                'name' => 'adex server 4',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'adex',
            ],
            [
                'base_url' => '#',
                'name' => 'adex server 5',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'adex',
            ],
            [
                'base_url' => '#',
                'name' => 'spurs server 1',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'spurs',
            ],
            [
                'base_url' => '#',
                'name' => 'spurs server 2',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'spurs',
            ],
            [
                'base_url' => '#',
                'name' => 'spurs server 3',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'spurs',
            ],
            [
                'base_url' => '#',
                'name' => 'spurs server 4',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'spurs',
            ],
            [
                'base_url' => '#',
                'name' => 'spurs server 5',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'spurs',
            ],
            [
                'base_url' => '#',
                'name' => 'msorg server 1',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'msorg',
            ],
            [
                'base_url' => '#',
                'name' => 'msorg server 2',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'msorg',
            ],
            [
                'base_url' => '#',
                'name' => 'msorg server 3',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'msorg',
            ],
            [
                'base_url' => '#',
                'name' => 'msorg server 4',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'msorg',
            ],
            [
                'base_url' => '#',
                'name' => 'msorg server 5',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'msorg',
            ],
            [
                'base_url' => 'https://smeplug.ng/api/v1',
                'name' => 'sme plug',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'vendor',
                'sub_category' => 'simhost',
            ],
            [
                'base_url' => 'https://api.flutterwave.com/v3',
                'name' => 'flutterwave',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => 'FLWSECK-97e38b05b77a7b074bd4313a59d4dd30-18db89aa37bvt-X',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'payment',
                'sub_category' => 'payment',
            ],
            [
                'base_url' => 'https://api.monnify.com/api/v1',
                'name' => 'monnify',
                'username' => '4703191085',
                'password' => '03N5QXJFZW3XA4RNQTP6KNLNNDRW1T7X',
                'active' => 0,
                'api_key' => 'MK_TEST_449CZS5MX6',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'payment',
                'sub_category' => 'payment',
            ],
            [
                'base_url' => 'https://api.payvessel.com/',
                'name' => 'Payvessel',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => 'FLWSECK-97e38b05b77a7b074bd4313a59d4dd30-18db89aa37bvt-X',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'payment',
                'sub_category' => 'payment',
            ],

            [
                'base_url' => 'https://api.paymentpoint.co/api/v1',
                'name' => 'payment point',
                'username' => '#',
                'password' => '#',
                'active' => 0,
                'api_key' => '#',
                'auth_type' => 'token',
                'webhook_access' => '1',
                'category' => 'payment',
                'sub_category' => 'payment',
            ],
        ]);

    }
}
